### ISSUE TITLE
Button pressed state transition is slow

### ISSUE THREAD

**Issue by ebariaux** [openremote/iOS#23]
From user feedback: "the alteration between image and pressed image is somewhat slow. If I hit a control quickly, the alteration does not happen at all, while the function is carried out. If I keep the control pressed for about half a second the pressed image shows."

**Comment by gdurys** [comment]
This is due to the enclosing scrollview that intercepts touches for a small delay to determine if it must scroll or not. (delaysContentTouch == YES by default)

**Comment by gdurys** [comment]
We keep the standard behaviour.
