### ISSUE TITLE
Have auto-selection on panel based on heuristic

### ISSUE THREAD

**Issue by ebariaux** [openremote/iOS#30]
Based on the name of the panel and the device the application is running on, auto-select the panel the first time a controller is added.

The selection is based on the fact that the panel name starts with a predefined prefix as follows (use case insensitive comparison):
"iPhone" -> all 3.5" non retina screens
"iPhone4" -> all 3.5" retina screens
"iPhone5" -> all 4" screens
"iPhone6" -> all 4.7" screens
"iPhone6Plus" -> all 5.5" screens
"iPad" -> all non retina iPads
"iPad3" -> all non 12.9" retina iPads
"iPadPro12" -> iPad Pro 12.9"

**Comment by gdurys** [comment]
"iPhone" won't be used: last non-retina 3.5" iPhone is the 3GS (max iOS 6) and last non-retina 3.5" iPod Touch is iPod Touch 3G (max iOS 5)
