### ISSUE TITLE
Update automatic panel selection mechanism

### ISSUE THREAD

**Issue by ebariaux** [openremote/iOS#34]
Automatic panel selection based on name prefix compared to device model should be updated to support new models: iPhone 7, 7P, 8, 8P, X, XS, XR and iPad 11"

**Comment by gdurys** [comment]
Prefixes added: 
 * `iPhoneX` (iPhoneX, iPhone XS)
 * `iPhoneXSMax` 
 * `iPhoneXR`
 * `iPadPro11`

iPhone 7 and 8 will use `iphone6` prefix.
iphone 7Plus and 8Plus will use `iphone6Plus` prefix.

**Comment by ebariaux** [comment]
What about iPad 10.5", 2224x1668 resolution ?

**Comment by gdurys** [comment]
I added `iPadPro105` for the iPad Pro 10.5"
